#!/bin/bash

# removing trap

trap "echo 'Bye from trapped EXIT'" EXIT

count=1
while [ $count -le 5 ]
do
  echo "Loop #$count"
  sleep 3
  count=$[ $count + 1 ]
done
trap - EXIT
echo " I just removed the trap from EXIT"

# THE SCRIPT IGNORES THE SIGNALS. 
# IF A SIGNAL IS RECEIVED BEFORE THE TRAP IS REMOVED: IT EXECUTED THE COMMAND INSIDE TRAP
