#!/bin/bash

# -d option tells the mktemp command to create a temporary directory instead of a file.

# using a temporary directory

tempdir=`mktemp -d dir.XXXXXX`
cd $tempdir
tempfile1=`mktemp temp.XXXXXX`
tempfile2=`mktemp temp.XXXXXX`
exec 7> $tempfile1
exec 8> $tempfile2

echo "Sending data to directory $tempdir"
echo "This is a test line of data for $tempfile1" >&7
echo "This is a test line of data for $tempfile2" >&8

# ls -al
# cd dir.
# cat temp.
# script creates a directory in the current directory and then 
# it uses the cd command to change to that directory before creating two temporary files. 
# The two temporary files are then assigned to file descriptors and used to store output from the scripts 
