#!/bin/bash

BEGIN {
print " The latest list of users and shells"
print " Userid			Shell "
print "----------	       -------------"
FS=":"
}
{
print $1 "			" $7 
}	
END {
print "This concludes the listing"
}

# run outside
# gawk -f 05_script /etc/passwd
