#!/bin/bash

# Reading Data from a file 
# [address]r filename  
# filename spesifies either an absolute or relative pathname for the file that contains data
# we cannnot use range of addresses for the read command
# only single line number or text patter address.

# sed editor inserts the text from the file after the address

echo " ---- Reading Data from a file --- "
echo " reads data from read_file and insertes after the specified address "
sed '3r read_file' data_file

echo ""
echo " --- Reads using Text pattern --- "
sed '/Three The/r read_file' data_file


echo ""
echo "--- Add string to the end of data stream ---"
echo ""
sed '$r read_file' data_file
