#!/bin/bash

echo " -- Content of data_file4 --"
cat data_file4
echo
echo " -- Check the value greater than 20 (If statement) --"
gawk '{
if ($1 > 20)
  print $1
}' data_file4

# use curly braces for multiple lines of statement
echo
echo " --- If Else statement ---"
gawk '{
if ($1 > 20)
{
  x = $1 * 2
  print x
} else
{
  x = $1 / 2
  print x
}}' data_file4


# Single line format
# gawk '(if ($1>20) print $1 * 2; else print $1 / 2}' data_file4
