#!/bin/bash

# deleting blank lines as the end of a data stream requires a little ingenuity and looping.

sed '{
:start
/^\n *$/{
$d
N
b start }
}' data_file3

# there are braces within the normal script braces.
# This allows you to group commands together within the overall command script.
# The group of commands applies to the specified address pattern.
# The address pattern matches any line that contains only a newline character.
# When one is found, if it's the last line, the delete command deletes it.
# If it's not the last line, the N command appends the next line to it, and the branch command loops to the beginning to start over.

