#!/bin/bash

# score of variable : Local & Global

# Global Variables

echo " ---------------------------------"
echo " GLOBAL VARIABLES "
echo " ---------------------------------"

# any variables defined in the script are global variables.
# using global variable to pass the value

function dbl {
  value=$[ $value * 2 ]	# value is a global variable
}
read -p " Enter a value: " value
dbl
echo " The new value is : $value"


echo " _____________________________________________________________________________"
echo " ---------------------------------"
echo " LOCAL VARIABLES "
echo " ---------------------------------"
# local variablename=value

function trpl {
  local temp=$[ $value + 5 ]
  result=$[ $temp * 3 ]
temp=2
value=3
trpl
echo "The result is $result "
if [ $temp -gt $value ]
then
  echo "temp is larger"
else
  echo "temp is smaller"
fi
}
