#!/bin/bash

function double_array {
  local origarray
  local newarray
  local elements
  local i

  origarray=(`echo "$@"`)
  newarray=(`echo "$@"`)
  elements=$[ $# - 1 ]
  for (( i = 0; i <= $elements ; i++ ))
  {
    newarray[$i]=$[ ${origarray[$i]} * 2 ]
  }
  echo ${newarray[*]}
}

myarray=(1 2 3 4)
echo " The original array is : ${myarray[*]} "
arg1=`echo ${myarray[*]}`
result=(`double_array  $arg1`)
echo "The new array is: ${result[*]]"
